import type { NextPage } from "next";
import Head from "next/head";
import Task from "../components/Task";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  const tasks = [
    "aprender react hooks contruyendo un custom cursor",
    "armar el formulario on click",
    "aprender trpc para crear el endpoint",
    "aplicar estilos faltantes",
  ];
  const taskElements = tasks.map((task) => {
    return <Task goal={task} />;
  });

  return (
    <>
      <Head>
        <title>Ideally</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-neutral-100 h-screen flex flex-col items-center cursor-none font-serif text-zinc-800">
        <div className="bg-emerald-100 w-20 h-20 rounded-full text-6xl flex items-center justify-center">
          <div className="bg-indigo-800 h-12 w-2 absolute"></div>
          <div className="bg-indigo-800 h-12 w-2 absolute rotate-90"></div>
        </div>
        <h1 className="text-8xl pt-10 tracking-tight text-black">Ideally,</h1>
        <h2 className="text-6xl py-10 tracking-tighter">
          what would you like to do today?
        </h2>
        <div className="w-1/2 space-y-4">{taskElements}</div>
      </div>
    </>
  );
};

export default Home;
